"use client"
import "./globals.css";
import { usePathname } from "next/navigation";

import FloatingDockDemo from "./navigation";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "../lib/utils"
import { WavyBackground } from "@/components/ui/wavy-background";
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const pathname = usePathname();
  return (
    <html lang="en">
    <head>
        <title>Pharm</title>
        <meta charSet="utf-8" />
    </head>
    <body>

        {<FloatingDockDemo/>}
        
        {children}
        <div className="h-0 w-full bg-white flex flex-col items-center justify-center antialiased">
        {(pathname=="/" || pathname=="/login" || pathname=="/logout" || pathname=="/signup") && <WavyBackground/>}
        </div>
    </body>
    </html>
  );
}
